apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" .Release.Name "application" | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: application
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: application
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.backend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: application
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.containerPort }}
          {{- with .Values.backend.envFromSecrets }}
          envFrom:
            {{- range . }}
            - secretRef: { name: {{ . | quote }} }
            {{- end }}
          {{- end }}
          {{- with .Values.backend.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.backend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.backend.readinessProbe | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","sleep {{ .Values.backend.lifecycle.preStopSleepSeconds }}"]
      {{- if .Values.backend.mysqlCaSecret.enabled }}
      volumes:
        - name: mysql-ca-vol
          secret:
            secretName: {{ .Values.backend.mysqlCaSecret.name }}
            items:
              - key: {{ .Values.backend.mysqlCaSecret.key }}
                path: {{ .Values.backend.mysqlCaSecret.key }}
                mode: {{ .Values.backend.mysqlCaSecret.mode }}
      {{- end }}